import random
import math
from environment import Agent, Environment
from planner import RoutePlanner
from simulator import Simulator

class LearningAgent(Agent):
    """ An agent that learns to drive in the Smartcab world.
        This is the object you will be modifying. """ 

    def __init__(self, env, learning=True, epsilon=1.0, alpha=0.5):
        super(LearningAgent, self).__init__(env)     # Set the agent in the evironment 
        self.planner = RoutePlanner(self.env, self)  # Create a route planner
        self.valid_actions = self.env.valid_actions  # The set of valid actions

        # Set parameters of the learning agent
        self.learning = learning # Whether the agent is expected to learn

        # Create a Q-table which will be a dictionary of tuples
        self.Q = dict() 

        self.epsilon = epsilon   # Random exploration factor
        self.alpha = alpha       # Learning factor

        # Set any additional class parameters as needed
        self.createQ()


    def reset(self, destination=None, testing=True):
        """ The reset function is called at the beginning of each trial.
            'testing' is set to True if testing trials are being used
            once training trials have completed. """
        # Select the destination as the new location to route to
        self.planner.route_to(destination)
        # Update epsilon using a decay function of your choice
        

        # self.epsilon = self.epsilon - 0.01


        # Update additional class parameters as needed
        # If 'testing' is True, set epsilon and alpha to 0
        # self.epsilon = 0
        # self.alpha = 0

        return None

    def build_state(self):
        """ The build_state function is called when the agent requests data from the 
            environment. The next waypoint, the intersection inputs, and the deadline 
            are all features available to the agent. """
        # Collect data about the environment
        waypoint = self.planner.next_waypoint() # The next waypoint 
        inputs = self.env.sense(self)           # Visual input - intersection light and traffic
        deadline = self.env.get_deadline(self)  # Remaining deadline
        # Set 'state' as a tuple of relevant data for the agent
        # When learning, check if the state is in the Q-table
        #   If it is not, create a dictionary in the Q-table for the current 'state'
        #   For each action, set the Q-value for the state-action pair to 0
        # state = (waypoint, inputs['light'], inputs['oncoming'])

        dict_state = {'direction' : waypoint, 'light' : inputs['light'], 'oncoming' : inputs['oncoming']}
        # dict_state_deadline = {'direction' : waypoint, 'light' : inputs['light'], 'oncoming' : inputs['oncoming'], 'deadline' : deadline}

        print (dict_state)
        print ('deadline : ', deadline)

        return dict_state


    def get_maxQ(self, state):
        """ The get_maxQ function is called when the agent is asked to find the
            maximum Q-value of all actions based on the 'state' the smartcab is in. """
        # Calculate the maximum Q-value of all actions for a given state
        action_dict = self.Q[state]

        max_key = max(action_dict, key=action_dict.get)
        max_value = action_dict[max_key]

        maxQ = max_key

        print('max_action : ' + str(max_key))
        print('max_value : ' + str(max_value))

        return maxQ 


    def createQ(self):
        """ The createQ function is called when a state is generated by the agent. """
        # When learning, check if the 'state' is not in the Q-table
        # If it is not, create a new dictionary for that state
        #   Then, for each action available, set the initial Q-value to 0.0

        # dict_state = {'light' : inputs['light'], 'oncoming' : inputs['oncoming'], 'direction' : waypoint}

        self.Q = {}

        valid_actions = self.valid_actions

        for direction in valid_actions :
            for light in ['green','red'] :
                for oncoming in valid_actions:
                    self.Q[(direction, light, oncoming)] = {'forward':0.0, 'left':0.0, 'right':0.0, None:0.0}

        print self.Q
        print len(self.Q)

        return


    def choose_action(self, state):
        """ The choose_action function is called when the agent is asked to choose
            which action to take, based on the 'state' the smartcab is in. """
        # Set the agent state and default action
        self.state = state
        self.next_waypoint = self.planner.next_waypoint()
        ###########
        # When not learning, choose a random action
        # action = random.choice(self.valid_actions)      
        # When learning, choose a random action with 'epsilon' probability
        #   Otherwise, choose an action with the highest Q-value for the current state

        if random.random() < self.epsilon:
            self.epsilon -= 0.01
            return random.choice(self.valid_actions)


        state_key = (state['direction'], state['light'], state['oncoming'])

        actionss = []
        Q_item = self.Q[state_key]
        max_Q = max(Q_item.values()) # find the max Q value

        print('max_Q - choose action : ', max_Q)
        
        for key, value in Q_item.iteritems():
            if value == max_Q:
                actionss.append(key)
        action = random.choice(actionss)

        print ('actionss : ', actionss)
        print('action - choose action : ', action)

        return action


    def learn(self, state, action, reward):
        """ The learn function is called after the agent completes an action and
            receives an award. This function does not consider future rewards 
            when conducting learning. """
        # When learning, implement the value iteration update rule
        #   Use only the learning rate 'alpha' (do not use the discount factor 'gamma')

        learning_rate = self.alpha
        gamma = 0.5
        # transform state to the Q dictionary key
        state_key = (state['direction'], state['light'], state['oncoming'])

        inputs = self.env.sense(self)
        direction = self.planner.next_waypoint()
        next_state_key = (direction, inputs['light'], inputs['oncoming'])

        max_Q = max(self.Q[next_state_key].values())

        print('max_Q - learn : ', max_Q)
        print('Q[state_key] : ', self.Q[state_key])
        print('Q[state_key][action] : ', self.Q[state_key][action])

        # Q learning equation
        # self.Q[state_key][action] = (1 - learning_rate) * self.Q[state_key][action] + learning_rate * (reward + gamma * max_Q)
        self.Q[state_key][action] = (1 - learning_rate) * self.Q[state_key][action] + learning_rate * (reward + 0 * max_Q)

        print('Q[state_key] : ', self.Q[state_key])
        print('Q[state_key][action] : ', self.Q[state_key][action])

        return


    def update(self):
        """ The update function is called when a time step is completed in the 
            environment for a given trial. This function will build the agent
            state, choose an action, receive a reward, and learn if enabled. """

        state = self.build_state()          # Get current state
        # self.createQ(state)                 # Create 'state' in Q-table
        action = self.choose_action(state)  # Choose an action
        # if action != 'None' :
        reward = self.env.act(self, action) # Receive a reward
        self.learn(state, action, reward)   # Q-learn

        return
        

def run():
    """ Driving function for running the simulation. 
        Press ESC to close the simulation, or [SPACE] to pause the simulation. """

    ##############
    # Create the environment
    # Flags:
    #   verbose     - set to True to display additional output from the simulation
    #   num_dummies - discrete number of dummy agents in the environment, default is 100
    #   grid_size   - discrete number of intersections (columns, rows), default is (8, 6)
    env = Environment(verbose=True)
    
    ##############
    # Create the driving agent
    # Flags:
    #    * learning   - set to True to force the driving agent to use Q-learning
    #    * epsilon - continuous value for the exploration factor, default is 1
    #    * alpha   - continuous value for the learning rate, default is 0.5
    agent = env.create_agent(LearningAgent, learning=True, alpha=0.5, epsilon=0.1)
    
    ##############
    # Follow the driving agent
    # Flags:
    #   enforce_deadline - set to True to enforce a deadline metric
    env.set_primary_agent(agent, enforce_deadline=True)

    ##############
    # Create the simulation
    # Flags:
    #   update_delay - continuous time (in seconds) between actions, default is 2.0 seconds
    #   display      - set to False to disable the GUI if PyGame is enabled
    #   log_metrics  - set to True to log trial and simulation results to /logs
    #   optimized    - set to True to change the default log file name
    sim = Simulator(env, update_delay=0.01, log_metrics=True, optimized=True, display=False)
    
    ##############
    # Run the simulator
    # Flags:
    #   tolerance  - epsilon tolerance before beginning testing, default is 0.05 
    #   n_test     - discrete number of testing trials to perform, default is 0
    sim.run(n_test=20, tolerance=0.01)


if __name__ == '__main__':
    run()
