import random
import math
from environment import Agent, Environment
from planner import RoutePlanner
from simulator import Simulator

class LearningAgent(Agent):
    """ An agent that learns to drive in the Smartcab world.
        This is the object you will be modifying. """ 

    def __init__(self, env, learning=False, epsilon=1.0, alpha=0.5):
        super(LearningAgent, self).__init__(env)     # Set the agent in the evironment 
        self.planner = RoutePlanner(self.env, self)  # Create a route planner
        self.valid_actions = self.env.valid_actions  # The set of valid actions

        # Set parameters of the learning agent
        self.learning = learning # Whether the agent is expected to learn

        # Create a Q-table which will be a dictionary of tuples
        self.Q = dict() 

        self.epsilon = epsilon   # Random exploration factor
        self.alpha = alpha       # Learning factor

        ###########
        ## TO DO ##
        ###########
        # Set any additional class parameters as needed


    def reset(self, destination=None, testing=True):
        """ The reset function is called at the beginning of each trial.
            'testing' is set to True if testing trials are being used
            once training trials have completed. """

        # Select the destination as the new location to route to
        self.planner.route_to(destination)
        
        ########### 
        ## TO DO ##
        ###########
        # Update epsilon using a decay function of your choice
        self.epsilon = self.epsilon - 0.01

        # Update additional class parameters as needed
        # If 'testing' is True, set epsilon and alpha to 0
        # epsilon = 0
        # alpha = 0

        return None

    def build_state(self):
        """ The build_state function is called when the agent requests data from the 
            environment. The next waypoint, the intersection inputs, and the deadline 
            are all features available to the agent. """

        # Collect data about the environment
        waypoint = self.planner.next_waypoint() # The next waypoint 
        inputs = self.env.sense(self)           # Visual input - intersection light and traffic
        deadline = self.env.get_deadline(self)  # Remaining deadline

        ########### 
        ## TO DO ##
        ###########
        # Set 'state' as a tuple of relevant data for the agent
        # When learning, check if the state is in the Q-table
        #   If it is not, create a dictionary in the Q-table for the current 'state'
        #   For each action, set the Q-value for the state-action pair to 0
        state = (waypoint, inputs['light'], inputs['oncoming'])

        dict_state = {'light' : inputs['light'], 'oncoming' : inputs['oncoming'], 'direction' : waypoint}

        # if (self.Q.has_key(state) == False) :
        #     d_new = {}
        #     for i in state :
        #         d_new[i] = 0
        #     self.Q[state] = d_new

        return state


    def get_maxQ(self, state):
        """ The get_maxQ function is called when the agent is asked to find the
            maximum Q-value of all actions based on the 'state' the smartcab is in. """

        ########### 
        ## TO DO ##
        ###########
        # Calculate the maximum Q-value of all actions for a given state
        action_dict = self.Q[state]

        max_key = max(action_dict, key=action_dict.get)
        max_value = action_dict[max_key]

        maxQ = max_key

        print('max_action : ' + str(max_key))
        print('max_value : ' + str(max_value))

        return maxQ 


    def createQ(self, state):
        """ The createQ function is called when a state is generated by the agent. """

        ########### 
        ## DONE ##
        ###########
        # When learning, check if the 'state' is not in the Q-table
        # If it is not, create a new dictionary for that state
        #   Then, for each action available, set the initial Q-value to 0.0
        if (self.Q.has_key(state) == False) :
            d_new = {}
            # j = 1
            for i in state :
                # strg =  str(j) + ' : ' + str(i)
                d_new[i] = 0.0
                # j += 1
            self.Q[state] = d_new

            # print(self.Q)

        return


    def choose_action(self, state):
        """ The choose_action function is called when the agent is asked to choose
            which action to take, based on the 'state' the smartcab is in. """

        # Set the agent state and default action
        self.state = state
        self.next_waypoint = self.planner.next_waypoint()
        

        ########### 
        ## TO DO ##
        ###########
        # When not learning, choose a random action
        # action = random.choice(self.valid_actions)
        
        # When learning, choose a random action with 'epsilon' probability
        #   Otherwise, choose an action with the highest Q-value for the current state
        # action = self.get_maxQ( state)
        action_dict = self.Q[state]

        max_key = max(action_dict, key=action_dict.get)
        max_value = action_dict[max_key]

        maxQ = max_key

        print('max_action : ' + str(max_key))
        print('max_value : ' + str(max_value))

        action = self.get_maxQ(state)
        print('action : ' + str(action))

        if action not in self.valid_actions :
            action = random.choice(self.valid_actions)

        inputs = self.env.sense(self) 
        if inputs['light'] == 'red' :
            action = None  
 
        return action


    def learn(self, state, action, reward):
        """ The learn function is called after the agent completes an action and
            receives an award. This function does not consider future rewards 
            when conducting learning. """

        ########### 
        ## TO DO ##
        ###########
        # When learning, implement the value iteration update rule
        #   Use only the learning rate 'alpha' (do not use the discount factor 'gamma')
        action_dict = self.Q[state]

        max_key = max(action_dict, key=action_dict.get)
        curr_max_value = action_dict[max_key]

        new_state = self.build_state()
        self.createQ(new_state)
        new_action_dict = self.Q[new_state]

        new_max_key = max(new_action_dict, key=new_action_dict.get)
        new_max_value = new_action_dict[new_max_key]

        learned_value = reward + (0.5 * new_max_value)
        new_q_value = curr_max_value + self.alpha * (learned_value - curr_max_value)

        action_dict[max_key] = new_q_value
        self.Q[state] = action_dict

        return


    def update(self):
        """ The update function is called when a time step is completed in the 
            environment for a given trial. This function will build the agent
            state, choose an action, receive a reward, and learn if enabled. """

        state = self.build_state()          # Get current state
        self.createQ(state)                 # Create 'state' in Q-table
        action = self.choose_action(state)  # Choose an action
        # if action != 'None' :
        reward = self.env.act(self, action) # Receive a reward
        self.learn(state, action, reward)   # Q-learn

        return
        

def run():
    """ Driving function for running the simulation. 
        Press ESC to close the simulation, or [SPACE] to pause the simulation. """

    ##############
    # Create the environment
    # Flags:
    #   verbose     - set to True to display additional output from the simulation
    #   num_dummies - discrete number of dummy agents in the environment, default is 100
    #   grid_size   - discrete number of intersections (columns, rows), default is (8, 6)
    env = Environment()
    
    ##############
    # Create the driving agent
    # Flags:
    #    * learning   - set to True to force the driving agent to use Q-learning
    #    * epsilon - continuous value for the exploration factor, default is 1
    #    * alpha   - continuous value for the learning rate, default is 0.5
    agent = env.create_agent(LearningAgent, learning=True, alpha=0.5, epsilon=0.1)
    
    ##############
    # Follow the driving agent
    # Flags:
    #   enforce_deadline - set to True to enforce a deadline metric
    env.set_primary_agent(agent, enforce_deadline=True)

    ##############
    # Create the simulation
    # Flags:
    #   update_delay - continuous time (in seconds) between actions, default is 2.0 seconds
    #   display      - set to False to disable the GUI if PyGame is enabled
    #   log_metrics  - set to True to log trial and simulation results to /logs
    #   optimized    - set to True to change the default log file name
    sim = Simulator(env, update_delay=0.01, log_metrics=True, optimized=False)
    
    ##############
    # Run the simulator
    # Flags:
    #   tolerance  - epsilon tolerance before beginning testing, default is 0.05 
    #   n_test     - discrete number of testing trials to perform, default is 0
    sim.run(n_test=25)


if __name__ == '__main__':
    run()
